language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "XtDnoSkZvemEat1oql7APY7AOFkA9P8RYGtFwUs0RFIVWf0C+YSo74m+SehHR7D4vPoVsd4pbTro6CAUqARmOctoQU6HLbeChJLG70ijPPnqei0HNthexnrqq3zunz/NaaM/8/bZV4lbrJHmzmdsLK3Fg/GykhJ+7+fViI3uqGIx9ElwXdKMt7G7K14AI1O50kQHG0Nag3JCyvkidaAUo8R0l7UqThJ39bDKDH41RZunb5Z4A70cH51ksSbej4i5uTdn6N5P2ncdVJ19JEJ79YAkYkq9XoXW+DrHdYie6h4uZvf21bBlOdvjpvmqpOJeYXZ3xMF1LSMZkWK5fzyjAFfgrZVYXALfoFFZmSiuAb+/haeNnOy2j5gIZp89GJ1AhKQRM6c2JDeArDmfzYp7SeJcAAJlc3mJz/7IueY7zXzwjlGOvhGuRrY7WXMMdc2iUk3vczhuEAtRbrFxCWnhna8ej+Oa3ucrYfz7JiTwotQV7br44a7Wpm+v3ADY+/C/Gg1zacGPgKbRkxQSV0+lR1bMTKe/bsYTc3fN32qdrJEubfdjmv9ZogYOkxvX2HGyKQBFqJKvyVbeGcks+7gv6rjnkNV0qPjlA4YVu9GkHcdvpxOJddyAtH5yf2KCrAQ7VNXMHRiMeaKq/6yiT1xE1+eVkvTFaN6fzCC72/dSDGY="
    - secure: "aSHYe1I7j9ySV6Jo+WLRr5Ecvi71Ff/nby10BIg7WfkYbsvYDn9pQxthUtZMbJDA5rlaW3FQrjmFgQ+7Qb3BqzfzUYqhqB43Yo9mMNcgjcyeRRjCBvXHFn2mJFvbvtsGHqUZI5IHWTOopFmQmlWKFm8hbeGyCec4PPYByiD/UhbdW0yR9tplBhDOJjXbZVkcxR6OvPgjDzgA77WyPRB9BdPPJJ4Q0nzWG8EgGyXP2LxsEhkojmBPJkzXjvtb0zM0T+9Hj3n3D2Ixi8gHmeN4JKLJPiWSeWkPtBkbEiFzObqPhq4CE1qIJMW5+yn7pYigVvm2+AjqxB0DqsVfHXvqhm2DRe9MoK+NIqD9WGCXyfRczmhxtJ2o5a5ONtxQRLPkBEd8W9iXDAV+rvHywaKEwSmgQVnz5Ga+UY1Dio7tu9bk8UpZ2XE5lYFirdPDjtUFhwUvgzuVcT2CKxA4w3RSFoOPY5+GOssbJrklHdbIbI8nMjzOJIO/Qvdl+a7pSG9fqj74vroH8bat7MtV9GlPP7ONI4IflwqS6azbEWp28HJ5h2yVRT5odNOclN1/8wqcVn1zHs4jKP/1tUiycoNOttQ7NMKVsW8EVBHYxLRS7hAC4l5aSw7aKdjO53NV2bAFG8c/ZpSkz2X5CQLRhNc1bqDYZwJjVdUPQGRVvZ5T4M4="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
